### ISSUE TITLE
Soundscape sharing mechanism - please continue to make available post 30th June!

### ISSUE THREAD

**Issue by jchudge** [microsoft/soundscape#10]
As I understand it, after 30th June, Microsoft will turn off the data services associated with Soundscape. However, it will be important for existing users of the app to be able to transfer their current Markers and Routes to any new version of Soundscape that may be forthcoming. Hence, I would like to ask Microsoft to leave the current ‘sharing mechanism’ for at least 3 months after the end of June, so that it could potentially be used to support existing users with the migration of their personalised markers and routes!

**Comment by AdamGlass** [comment]
I recognize your concern but i'm not sure if the sharing mechanism would continue to work if the other services are shutdown.  Question is best addressed to robinmo@microsoft.com .   @mekne @datsirul
