### ISSUE TITLE
Use of the name Soundscape

### ISSUE THREAD

**Issue by bramd** [microsoft/soundscape#13]
I was wondering if the name Soundscape is protected in any way. E.g. would ik be OK if an app built on this open source release would be named Soundscape (of course with different producer/company name and no MS branding at all)?

I'm not sure if it would be a good idea to keep the name, but just exploring if this is even an option.

**Comment by AdamGlass** [comment]
Nobody on github can answer your question with any authority.  In particular we're not lawyers.  Microsoft has a lot of lawyers.

I do note that Microsoft removed the Soundscape branding from the open source version specifically to avoid having a reconstituted version to appear as a Microsoft *product* even by appearance.

If someone wants a formal answer, they can try reaching out to robinmo@microsoft.com
