### ISSUE TITLE
VM/CPU capacity/specification

### ISSUE THREAD

**Issue by calistairforbes** [microsoft/soundscape#16]
Issue #8 asked about the cost breakdown for the backend service and the response explained that it was difficult to give costings for a number of reasons - is it possible to get information on the specification of the VM instance being used currently to run the service? That doesn't necessarily mean that it would be the right spec going forward and appreciate that no advice can be given on that.

**Comment by AdamGlass** [comment]
the file svcs/data/misc/soundscape_provision.py has an excerpt from the deployment script for a version of the services.  The resources listed under the 'production' configuration are similar if not identical to those used in the last production deployment.  Any difference might reflect different behavior between the imposm and osm2pgsql variations of the services.

All of my past comments re: not making too many assumptions based on the resources we used, cost, etc. still apply.

**Comment by calistairforbes** [comment]
Thanks @AdamGlass - much appreciated.
