### ISSUE TITLE
File formats for import/export

### ISSUE THREAD

**Issue by calistairforbes** [microsoft/soundscape#17]
Users can save information in the app, and can import and export it - we understand that there are two file formats, JSON and a proprietary format. 
Is it possible to get documentation around the file formats with a view to being able to import from the proprietary files into a new version of the app?

**Comment by AdamGlass** [comment]
I don't recall any import or export functionality in the app.  @mekne?

**Comment by calistairforbes** [comment]
Thanks @AdamGlass - maybe not explicitly import/export but the ability to save markers, etc ...

**Comment by datsirul** [comment]
I'm assuming you are referring to the user created `Route` objects which can be exported via files. Other data, such as `Marker` objects are exported via URLs.

Regarding the `Route` file format - it's a JSON file, where the route ID is the file name, and it has a custom extension `.soundscape`.

The file is an external representation of the `RouteParameters` object, which is responsible for representing `Route` objects when exporting and importing.
As `RouteParameters` conforms to the `Codable` protocol, it can be serialized into JSON.
