### ISSUE TITLE
Server cutoff date

### ISSUE THREAD

**Issue by steinbro** [microsoft/soundscape#18]
I got a push notification from Soundscape the other day that suggested the app's services would be turned off at the end of August, not June as originally announced in December. Is this correct? I can't find confirmation of this anywhere.

**Comment by datsirul** [comment]
Yes, you are correct. As noted in the updated blog post:

> Editor’s note, June 19, 2023 – The date existing installations of the Soundscape iOS app can continue to be used has been extended to Aug. 30, 2023. The article has been updated to reflect that change.

Link: https://aka.ms/ossblog
