### ISSUE TITLE
Bing key?

### ISSUE THREAD

**Issue by dumbledad** [microsoft/soundscape#2]
The blind kid I mentor is hoping to pick this up and try to get it working. Will we need any Bing Maps keys, or are the maps, waypoints, places of interest, etc. ingested purely from Open Street Maps?

**Comment by mikedoise** [comment]
I have personally been able to get the app to compile, but I have not been able to create the back end for it. I would love to help bring the app back if someone could help me set up the back end. There are several components that have to be used from what I saw in the documentation.

**Comment by AmosMiller** [comment]
The open source version here uses only OSM for map data. The back-end services rendor the OSM planet map and serve the tiles to the app. For open search we will need to pull in another map provider e.g. Google.

**Comment by rogerdac** [comment]
How much work is involved in moving over to google.

**Comment by AdamGlassMS** [comment]
I can't comment on the specific work to move to google.

I can however suggest a data sources evaluation criteria:
* Cost per query -- 'points of interest' data is considered highly valuable and per query can reflect that
* Restrictions in use - data sources often have substantial restrictions in how they can be used, cached, mixed with other data sources, etc.
* Coverage/Quality - data sources in this space have highly varied levels of coverage/quality depending on where you're searching,

**Comment by rogerdac** [comment]
Hi Adam
Ok
I notice that Sony have removed the support for the application. Does this mean that the current project will no longer be viable.
There looks a lot of work has gone into the Guide dog app and that the backend could be replaced with many different solutions.
If you cannot comment on this which I fully understand.

Roger Parker | E-learning Support Team

Digital Accessibility Centre
T: 07539710839
E: ***@***.******@***.***>
W: www.digitalaccessibilitycentre.org<https://gbr01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.digitalaccessibilitycentre.org%2F&data=05%7C01%7Croger.parker%40digitalaccessibilitycentre.org%7C39dbad5b0d15421c645e08da5dc4d797%7C6cc99ebe9e6a4e39b564e5e9f1736548%7C1%7C0%7C637925397251755419%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jwKnmhJSSZAsckybMWfqbAD0kCqHroF%2FTtunfSKYrpI%3D&reserved=0>
Twitter: www.twitter.com/DACcessibility<https://gbr01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.twitter.com%2FDACcessibility&data=05%7C01%7Croger.parker%40digitalaccessibilitycentre.org%7C39dbad5b0d15421c645e08da5dc4d797%7C6cc99ebe9e6a4e39b564e5e9f1736548%7C1%7C0%7C637925397251755419%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WIs7SPQMNK9mncrmn%2Fosy2SmL1wdKSH3O2BRegUKxGs%3D&reserved=0>

[DAC Logo]





From: Adam Glass (microsoft) ***@***.***>
Date: Sunday, 15 January 2023 at 17:18
To: microsoft/soundscape ***@***.***>
Cc: Roger Parker ***@***.***>, Comment ***@***.***>
Subject: Re: [microsoft/soundscape] Bing key? (Issue #2)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

I can't comment on the specific work to move to google.

I can however suggest a data sources evaluation criteria:

  *   Cost per query -- 'points of interest' data is considered highly valuable and per query can reflect that
  *   Restrictions in use - data sources often have substantial restrictions in how they can be used, cached, mixed with other data sources, etc.
  *   Coverage/Quality - data sources in this space have highly varied levels of coverage/quality depending on where you're searching,

**Comment by AdamGlassMS** [comment]
@rogerdac Roger: can you open a separate issue on your Sony question and make it a bit more clear whether you're referring to the open source offering, the product that is being sunset, etc.

**Comment by AdamGlassMS** [comment]
I think we've answered the Bing question the best we can -- if you experiment in this area, make sure you really understand the costs/licensing restrictions before you ship.
